#!/usr/bin/perl -w

use Bio::SeqIO;

#modify the inputfile filename as needed
$inputfile = "SampleFile.txt";

# you shouldn't have to modify anything below this line
$debug=1; #set to 1 for some debugging output

$nSilent=20;

@index = ("1-81-S2 (ref)", #{{{
"1c1",
"1c2",
"1c3",
"1c4",
"1c5",
"2c1",
"2c2",
"2c3",
"2c4",
"2c5",
"2c6",
"3c1",
"3c2",
"3c3",
"6c1",
"6c2",
"6c3",
"7c1",
"uss"); #}}}

@R1=("CGTCACCGAGTATTACCTGAATC", #{{{
"CGTTGCCGGGTATTGCCCGAATC",
"CGTTACCGGGTATTGCCCGAATC",
"CGTTGCCGGGTATTGCCCGAATC",
"AGTTGCCGGGTATTGCCTGAATC",
"CGTTACCGAGTATTACCTGAATC",
"CGTCACCGAATATTACCCGAATA",
"CGTTACCGAGTATTGCCCGAATC",
"CGTTACCGAGTATTACCTGAATC",
"GGTTGCCGGGTATTGCCTGAATC",
"CGTTGCCGGGTATTACCTGAATC",
"CGTTACCGGGTATTGCCCGAATC",
"CGTTGCCGGGTATTACCTGAATC",
"CCTCACCGAATATTACCTGAAA",
"CGTCACCGAGTATTACCTGAATC",
"CGTTACCGGGTATTACCTGAATA",
"CGTTGCCGGGTATTACCCGAATC",
"CGTCACCGAGTATTACCCGAATA",
"CGTCACCGAGTATTACCTGAATC",
"XXXX"); #}}}

@R2=("ATATGGCCGAAAGACAACACTTCT", #{{{
"ACATGGCCGAAAGACAACGGTGAT",
"AAATGGCCGAAAGACAACACTTCT",
"AAATGGCCGGAAAACAACACTTCT",
"GAATGGCCGGAAGACAACACTTCT",
"GAATGGCCCAAAGACAACGGCTCT",
"GAATGGCCCGCCGACAACGGCGCT",
"GAATGGCCGAAAGACAACGACAAG",
"ATATGGCCGGAAAACAACGACAAG",
"GAATGGCCGGAAGACAACACTTCT",
"GAATGGCCGGAAAACAACGACAAG",
"ATATGGCCGAAAGACAACACTTCT",
"GAATGGCCGGAAAACAACACTTCT",
"GAATGGCCCAAAGACAACGGCTCT",
"ATATGGCCGAAAGACAACACTTCT",
"AAATGGCCCGCCGACAACGGCGCT",
"AAATGGCCGGAAGACAACACTTCT",
"AAATGGCCCGCAAACAACGGCGCT",
"ACATGGCCGGAAAACAACACTTCT",
"ACATGGCCGAAAGACAACGGTGAT") ;#}}}

@R3=("TCCGCTTCAACAATCAA", #{{{
"TCCCCCGCCGACAAAATCAA",
"TCCCCCGCCGAAATCAA",
"TCCCCCCCCCTCCGACATCAA",
"TCCCCCCCCACCGACATCAA",
"TCCGCTTCAAAAATCAT",
"TCCGCTTCAACAATCAA",
"TCCCCCCCCTCCAACATCAA",
"TCTTCTTCATCAATCAA",
"TCCCCCCCACCGACATCAA",
"TCCGCCTCCGACATCAA",
"TCCTCCGCCGCCGACATCAA",
"TCCTCCGACAAAATCAA",
"TCCGCTTCAACAATCAA",
"AACCCCACCGACATCAA",
"TCCCCCGCCACCGACATCAA",
"TCCCCCCCTCCGACATCAA",
"TCCGCCTCCGACATCAA",
"TCCTCCGCCACCGACATCAA",
"TCCTCCGCCGAAATCAA"); #}}}

@R4=("CAGAAAGTTGAAGTCGCAAAA", #{{{
"CAGAAAGTTGAAGTCGCAAAA",
"AAAAGCGTTACGGTCGCAAAA",
"AAAGAGGTTGAAGTTAAAAAC",
"AAAAGCGTTACGGTCGCAAAA",
"AAGGAAGTTAAAGTCGAAAAC",
"CAGAAAGTTGAAGTCGCAAAA",
"GAAAGCGTTACGGTCACAAAC",
"AAGGAAGTTAAAGTCGAAAAC",
"AAAAGCGTTACGGTCGCAAAA",
"AAAAGCGTTACGGTCGCAAAA",
"CAGAAAGTTGAAGTCAACAAC",
"CAGAAAGTTGAAGTCGCAAAA",
"CAGAAAGTTGAAGTCACAAAC",
"GAAAGCGTTACGGTCACAAAC",
"AAGGAAGTTAAAGTCGAAAAC",
"CAAAGCGTTACGGTCGCAAAC",
"GAAAGCGTTACGGTCGAAAAA",
"CAAAGCGTTACGGTCGCAAAC",
"AAAAGCGTTACGGTCGCAAAC"); #}}}

@R5=("AGGCGTCGTTACCGCCCA", #{{{
"AGGCGTCGTTACCGCCGA",
"AGGCGTCGTTACCGCCCA",
"CGGCGTCGTTACCGCCAC",
"AGGCGTCGTCACCGCCGA",
"CGGCGTCGTCACCGCCCA",
"AGGCGTCGTTACCGCCCA",
"CGGCGTCGTTACCGCCAC",
"CGGCGTCGTCACCGCCAC",
"AGGCGTCGTCACCGCCGA",
"AGGCGTCGTTACCGCCGA",
"CGGCGTCGTTACCGCCAC",
"AGGCGTCGTTACCGCCCA",
"CGGCGTCGTTACCGCCCA",
"CGGCGTCGTTACCGCCAA",
"CGGCGTCGTCACCGCCCA",
"CGGCGTCGTTACCGCCGA",
"AGGCGTCGTTACCGCCAA",
"CGGCGTCGTTACCGCCGA",
"CGGCGTCGTTACCGCCGA"); #}}}

@R6=("CAAATGGCTTCAACCGG", #{{{
"GAAATGAAACCAAGCGG",
"CAAATGAATCCAAGCGG",
"ACAATGCTTTCAAGCGG",
"GAAATGGCTTCAACCGG",
"CAAATGGCTTCAAGCAA",
"CAAATGGCTTCAACCGG",
"ACAATGCTTTCAAGCGG",
"ACAATGAATTCAAGCAA",
"GAAATGGCTTCAACCGG",
"GAAATGGCTTCAACCGG",
"ACAATGGCTTCAAGCAA",
"CAAATGGCTTCAACCGG",
"CAAATGGCTTCAACCGG",
"AAAATGCTTTCAAGCGG",
"CAAATGGCTTCAACCGG",
"GAAATGAAATCAGACGG",
"AAAATGCTTTCAAGCGG",
"GAAATGAAATCAGACGG",
"GAAATGGCTTCAAGCGG"); #}}}

@R7=("AGAAATCCAAGACAAAAA", #{{{
"AGAAATCAAAGGCAAAAA",
"TGAAATCAAAGACAAAAA",
"TGAAATCAAAGGCAAAAA",
"TGAAATCAAAGGCAAAAA",
"AGAAATCAAAGACAAAAA",
"AGAAATCCAAGACAAAAA",
"TGAAATCAAAGGCAAAAA",
"AGAAATCAAAGACAAAAG",
"TGAAATCAAAGGCAAAAA",
"AGAAATCCAAGGCAAAAA",
"AGAAATCCAAGGCAAAAG",
"AGAAATCCAAGGCAAAAA",
"AGAAATCAAAGGCAAAAA",
"AGAAATCCAAGGCAAAAG",
"TGAAATCAAAGGCAAAAA",
"AGAAATCAAAGGCAAAAA",
"AGAAATCCAAGGCAAAAA",
"AGAAATCCAAGGCAAAAG",
"AGAAATCAAAGGCAAAAG"); #}}}

@R8=("CCAAGCGTCAAGACGGTTC", #{{{
"CCAAGCGTGAAGACGGTTC",
"CCAAGCGTGAAAACGGTTC",
"CCAGGCGTGAAAACGGTTC",
"CCAAGCGTCAAGACGGTC",
"CCAAGCGTGAAAACGGTTC",
"CCAAGCGTCAAGACGGTTC",
"CCAAGCGTCAAGCCGGTTC",
"CCAAGCGTGAAAACGGTTC",
"CCAAGCGTCAAGACGGTTC",
"CCAAGCGTGAAAACGGTTC",
"CCAAGCGTGAAAACGGTC",
"CCAAGCGTCAAGACGGTTC",
"CCAGGCGTCAAGACGGTTC",
"CCAAGCGTGAAGCCGGTTC",
"CCAAGCGTCAAGACGGTTC",
"GCAGGCGTGAAAACGGTTC",
"CCAAGCGTGAAGCCGGTTC",
"CCAGGCGTGAAGCCGGTTC",
"CCAGGCGTCAAGACGGTTC"); #}}}

@R9=("ACGCGCACCGGCGACAACGACGACACCGTTGCCGACGCCAACAACGCCATCGAC", #{{{
"AAGCGCGACGCCGGCGCCAAAGCCGACGACGTCAAAGCCGACGCCGCCAACGCCATCGAA",
"ACGCGCAACGACGCCAAAGCCGACGCCAAAGACGACACCGTCACCGCCATCGAA",
"ACGCGCGCCAAAGCCGACGCCGACGCCGACGCCGCCGGCAAAGACACCACCAACATCGAC",
"AAGCGCGACGCCGGCGCCAAAACCGGCGCCGACGACGTCAAAGCCGACGGCAAAGACACCGACAAAATCAAC",
"AAGCGCACCGAAGCCAACGCCAAAGCCGGCACCGACGACGTCGCCAAAGACGACACCGCCGGCACCAAAATCGAC",
"ACGCGCACCGGCGACAACGACGACACCGTTGCCGACGCCAACAACGCCATCGAC",
"CAGCGCGCCAAAGCCGACGACGCCGTCACCGCCGACGCCAACAACGCCATCGAC",
"AAGCGCGCCAACGTTGCCGCCGCCAACGACGACGACGTTACCGACGACAAAAACAACAACGGCATCGAC",
"AAGCGCGCCGACAACAACGGCAACATTACCGCCGACAACGGCAACGCCATCGAA",
"AAGCGCACCGAAGCCAACGCCAAAGCCGGCACCGACGACGTCGCCAAAGACGACACCGCCGGCACCAAAATCGAC",
"ACGCGCGACGACAAAGCCAAAGACGACGTCAAAGCCGACGGCACCGCCGGCACCAAAATCGAC",
"ACGCGCAACGACGCCAAAGCCGACGACGTCAAAGCCGACGCCGCCAACGCCATCGAA",
"AAGCGCGACGACGCCGCCGCCAAAGACGACACCGTCACCGCCGACGCCACCGGCAACGACGGCAAAATCGAC",
"AAGCGCACCGAAGCCAACGCCGACGCCGCCGGCAAAGACACCACCAACGGCATCAAC",
"AAGCGCGACGCCGGCGCCAAAACCGGCGCCGACGACGTCAAAGCCGACGGCAACAACGGCATCAAC",
"AAGCGCGACGCCAACAACGCCAACAACGACGCCGTCACCGACGACACCACCGGCAACGGCAACGAAAAAATCGAA",
"AAGCGCAACGACGCCGCCAACGACGACGTTACCGACGACGCCGGCACCGACAACGGCGGCAAAGGCAAAATCGAC",
"ACGCGCGCCAAAGCCAAAGACGCCGACGACGTTACCGACGACGCCGGCACCCACAACGGCGGCAAAGGCAAAATCGAC",
"ACGCGCAACGACGCCGCCGACAACGACGACGTCGCCAAAGACGACGCCGCCGGCAACGCCATCGAA"); #}}}

@R10=("CGATGAATCATCTGCCACCTA", #{{{
"CGATGAATCATCTGCCACCTA",
"CGATGAATCATCTGCCACCTA",
"CGATGAATCATCTGCCGTT",
"CGATAAATCATCTGCCGTT",
"CGATGAATCATCGTTGCCGG",
"CGATAAACATGATGCCAAAGA",
"TGATACGTCATCTGCCAAA",
"CGATAAATCATCTGCCACCTA",
"CGATGAATCATCTGCCACCTA",
"CGATGAATCATCGTTGCCGG",
"CGATGAATCATCGTTGCCGG",
"CGATGAATCATCTGCCACCTA",
"CGATAAATCAACTGCCGTT",
"CGACCCGTTCTCTGCTAGC",
"CGATAAACATGATGCCAAA",
"CGATGAATCATCTGCCGTTTA",
"CGATAAATCAACTGCCGTT",
"CGATAAATCAACTGCCAAA",
"CGATGAACCAACTGCCACCTA"); #}}}

if ("Hello World" =~ /Hello/){
  print "dude, it worked!\n";
}

@R = (@R1, @R2);
print $R[0][0];

# read in the data file
$seqio_obj = Bio::SeqIO->new(-file => $inputfile, -format => "fasta" );

if ($debug==1){ # for testing 
  for ($i=0;$i<10;$i++){
    $seq_obj = $seqio_obj->next_seq;
  } 
  print $seq_obj->display_id."\n";
  print $seq_obj->desc."\n";
  print $seq_obj->seq."\n";

  for ($i=0; $i<$nSilent; $i++){
    if ( $seq_obj->seq =~ /$R1[$i]/ ){
      print $index[$i]." "
    } 
  } 


  exit;
}


